version: 2

# This is intentionally blank bc im too lazy to include tests in this example, but you should include tests
# These source models are a good place to test not_nulls and check for ids especially 